
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  username: 'username',
  password: 'password',
  name: 'name',
  role: 'role',
  avatar: 'avatar',
  pPOS: 'pPOS',
  pInventory: 'pInventory',
  pSales: 'pSales',
  pService: 'pService',
  pOrders: 'pOrders',
  pCustomers: 'pCustomers',
  pSettings: 'pSettings',
  cedula: 'cedula',
  phone: 'phone',
  photo: 'photo',
  birthday: 'birthday',
  gender: 'gender',
  address: 'address',
  salary: 'salary',
  hiredAt: 'hiredAt',
  cvData: 'cvData',
  dataFile: 'dataFile',
  createdAt: 'createdAt'
};

exports.Prisma.AttendanceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  checkIn: 'checkIn',
  checkOut: 'checkOut',
  notes: 'notes'
};

exports.Prisma.AbsenceScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  date: 'date',
  reason: 'reason',
  isJustified: 'isJustified'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  sku: 'sku',
  name: 'name',
  description: 'description',
  category: 'category',
  price: 'price',
  cost: 'cost',
  stock: 'stock',
  minStock: 'minStock',
  warehouse: 'warehouse',
  image: 'image',
  featured: 'featured',
  showInCatalog: 'showInCatalog',
  warrantyDays: 'warrantyDays',
  updatedAt: 'updatedAt'
};

exports.Prisma.StockMovementScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  quantity: 'quantity',
  type: 'type',
  reason: 'reason',
  user: 'user',
  date: 'date'
};

exports.Prisma.SaleScalarFieldEnum = {
  id: 'id',
  saleNumber: 'saleNumber',
  subtotal: 'subtotal',
  globalDiscount: 'globalDiscount',
  iva: 'iva',
  total: 'total',
  totalBs: 'totalBs',
  paymentMethod: 'paymentMethod',
  cashier: 'cashier',
  date: 'date',
  time: 'time',
  sessionId: 'sessionId',
  customerId: 'customerId',
  createdAt: 'createdAt',
  paymentProof: 'paymentProof',
  paymentRef: 'paymentRef'
};

exports.Prisma.CashSessionScalarFieldEnum = {
  id: 'id',
  openedAt: 'openedAt',
  closedAt: 'closedAt',
  openingBalance: 'openingBalance',
  closingBalance: 'closingBalance',
  cashier: 'cashier',
  status: 'status'
};

exports.Prisma.SaleItemScalarFieldEnum = {
  id: 'id',
  saleId: 'saleId',
  productId: 'productId',
  qty: 'qty',
  price: 'price',
  discount: 'discount',
  warrantyDays: 'warrantyDays'
};

exports.Prisma.ServiceTicketScalarFieldEnum = {
  id: 'id',
  tkNumber: 'tkNumber',
  customer: 'customer',
  phone: 'phone',
  device: 'device',
  serial: 'serial',
  issue: 'issue',
  diagnosis: 'diagnosis',
  status: 'status',
  cost: 'cost',
  warranty: 'warranty',
  warrantyDays: 'warrantyDays',
  date: 'date',
  parts: 'parts'
};

exports.Prisma.ServiceNoteScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  content: 'content',
  author: 'author',
  createdAt: 'createdAt'
};

exports.Prisma.ClosureScalarFieldEnum = {
  id: 'id',
  date: 'date',
  totalSales: 'totalSales',
  totalItems: 'totalItems',
  totalAmountUsd: 'totalAmountUsd',
  totalAmountBs: 'totalAmountBs',
  ivaTotal: 'ivaTotal',
  details: 'details',
  cashier: 'cashier'
};

exports.Prisma.SystemConfigScalarFieldEnum = {
  id: 'id',
  storeName: 'storeName',
  storeRIF: 'storeRIF',
  storeAddress: 'storeAddress',
  storePhone: 'storePhone',
  exchangeRateBCV: 'exchangeRateBCV',
  exchangeRateUSDT: 'exchangeRateUSDT',
  ivaPercent: 'ivaPercent',
  defaultWarrantyDays: 'defaultWarrantyDays',
  fidelityEnabled: 'fidelityEnabled',
  ptsPer10Usd: 'ptsPer10Usd',
  catalogUrl: 'catalogUrl',
  tunnelMode: 'tunnelMode',
  tunnelToken: 'tunnelToken',
  customDomain: 'customDomain',
  companyLogo: 'companyLogo',
  pPriceBond: 'pPriceBond',
  pPricePhoto: 'pPricePhoto',
  pPriceGlace: 'pPriceGlace',
  pPriceColorMult: 'pPriceColorMult',
  pPriceBWMult: 'pPriceBWMult',
  pPriceSimpleMult: 'pPriceSimpleMult',
  pPriceDoubleMult: 'pPriceDoubleMult',
  updatedAt: 'updatedAt'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  email: 'email',
  password: 'password',
  name: 'name',
  phone: 'phone',
  address: 'address',
  points: 'points',
  pendingDiscount: 'pendingDiscount',
  createdAt: 'createdAt'
};

exports.Prisma.OrderScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  total: 'total',
  status: 'status',
  createdAt: 'createdAt',
  paymentMethod: 'paymentMethod',
  paymentProof: 'paymentProof',
  paymentRef: 'paymentRef'
};

exports.Prisma.OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  productId: 'productId',
  qty: 'qty',
  price: 'price'
};

exports.Prisma.QuotationScalarFieldEnum = {
  id: 'id',
  number: 'number',
  customerName: 'customerName',
  customerEmail: 'customerEmail',
  customerPhone: 'customerPhone',
  subtotal: 'subtotal',
  globalDiscount: 'globalDiscount',
  iva: 'iva',
  total: 'total',
  notes: 'notes',
  validUntil: 'validUntil',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.QuotationItemScalarFieldEnum = {
  id: 'id',
  quotationId: 'quotationId',
  productId: 'productId',
  qty: 'qty',
  price: 'price',
  discount: 'discount'
};

exports.Prisma.LoyaltyRewardScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  pointsCost: 'pointsCost',
  isActive: 'isActive',
  type: 'type',
  value: 'value',
  showInCatalog: 'showInCatalog'
};

exports.Prisma.LoyaltyMovementScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  points: 'points',
  type: 'type',
  reason: 'reason',
  date: 'date'
};

exports.Prisma.PrintOrderScalarFieldEnum = {
  id: 'id',
  orderNumber: 'orderNumber',
  customerId: 'customerId',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  filename: 'filename',
  fileSize: 'fileSize',
  fileUrl: 'fileUrl',
  paperType: 'paperType',
  colorMode: 'colorMode',
  sides: 'sides',
  pages: 'pages',
  quantity: 'quantity',
  estimatedTotal: 'estimatedTotal',
  finalTotal: 'finalTotal',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  User: 'User',
  Attendance: 'Attendance',
  Absence: 'Absence',
  Product: 'Product',
  StockMovement: 'StockMovement',
  Sale: 'Sale',
  CashSession: 'CashSession',
  SaleItem: 'SaleItem',
  ServiceTicket: 'ServiceTicket',
  ServiceNote: 'ServiceNote',
  Closure: 'Closure',
  SystemConfig: 'SystemConfig',
  Customer: 'Customer',
  Order: 'Order',
  OrderItem: 'OrderItem',
  Quotation: 'Quotation',
  QuotationItem: 'QuotationItem',
  LoyaltyReward: 'LoyaltyReward',
  LoyaltyMovement: 'LoyaltyMovement',
  PrintOrder: 'PrintOrder'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
